# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: "%env(APP_SECRET)%"
    session: true
    # ВКЛЮЧАЕМ CSRF (важно!)
    csrf_protection: true
    # Сессии нужны для хранения CSRF-токена

    # enabled: true # можно и просто "true", но так нагляднее
    # cookie_samesite: lax # безопасное значение по умолчанию
    # cookie_secure: auto

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
